### ISSUE TITLE
Implement early stopping interface

### ISSUE THREAD

**Issue by cbecker** [Allardvm/LightGBM.jl#14]
Hello, first thanks for this amazing package :)

Recently we've done some changes in the LightGBM Api (Microsoft's upstream) to allow for early stopping at prediction time, which can speed up predictions significantly (https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/c_api.h#L644, the `parameter` string is what is new here)

I will be gone for two weeks so I won't be able to work on this, but I wanted to leave the issue open here to warn you about the possible incompatibility with the latest upstream, and also that it would be very useful to have early stopping working with LightGBM.jl.

**Comment by cbecker** [comment]
There's functionality that is still missing if we want to support early stopping, which is why I wouldn't close the issue. I can add this in a new PR, do you agree with having extra parameters passed to predict to choose which early stopping or prediction parameters to use? It would be of type IOConfig from what I remember.

**Comment by Allardvm** [comment]
Yeah, there's quite a lot of more recent LightGBM functionality missing. I'm happy to help merge a PR, so if you'd like to add something, you're more than welcome to.
