### ISSUE TITLE
Final Model Should Be Best Model By Early Stopping

### ISSUE THREAD

**Issue by brianhempel** [Allardvm/LightGBM.jl#20]
This could also be viewed as a documentation problem, but I will admit I was surprised by this behavior which suggests it might be considered a bug instead.

The `fit!` and `train` functions honor early stopping. But although the best iteration is reported to the console and the scores are truncated to the best iteration (`shrinkresults!`), it is apparently up to the user to read out the truncated scores and save a truncated model—by default, saving a model after training will save the last iteration, not the best.

But if the scores are truncated, shouldn't the model be truncated back to the best as well? There's a strange mismatch there. At a minimum it'd be great if the README had an example of reading the truncated scores to find the best iteration and explicitly truncate the model on save. Thanks.

**Comment by Allardvm** [comment]
Closing this in favour of the new (and maintained) repository located here: https://github.com/IQVIA-ML/LightGBM.jl .
