### ISSUE TITLE
Julia v1.0 compatibility

### ISSUE THREAD

**Issue by ValdarT** [Allardvm/LightGBM.jl#21]
Any plans to update this to Julia v1.0 in the near future?

**Comment by Benoit9** [comment]
I have tried the  @wakakusa PR: https://github.com/Allardvm/LightGBM.jl/pull/22
but I get an error running the tests on Julia 1.1.
Is there anyone around?

**Comment by wakakusa** [comment]
Sorry for the late reply.
Since runtest.jl was an error even in v0.6, it has not been modified to pass all tests.

**Comment by wakakusa** [comment]
@Benoit9 @ValdarT 
I am compatible with Julia v1.2 and LightGBM v2.3.0 and modified test.jl to work with Julia v1.2. #22

**Comment by Allardvm** [comment]
Closing this in favour of the new (and maintained) repository located here: https://github.com/IQVIA-ML/LightGBM.jl .
